import 'dart:convert';

// Generated by https://quicktype.io

class Friends {
  String? email;
  dynamic id;
  String? idAmig;
  String? latitud;
  String? longitud;
  String? nombre;
  String? url;

  Friends({
    this.email,
    this.id,
    this.idAmig,
    this.latitud,
    this.longitud,
    this.nombre,
    this.url,
  });

  Map<String, dynamic> toMap() {
    return {
      'email': email,
      'id': id,
      'id_amig': idAmig,
      'latitud': latitud,
      'longitud': longitud,
      'nombre': nombre,
      'url': url,
    };
  }

  factory Friends.fromMap(Map<String, dynamic> map) {
    return Friends(
      email: map['email'],
      id: map['id'],
      idAmig: map['id_amig'],
      latitud: map['latitud'],
      longitud: map['longitud'],
      nombre: map['nombre'],
      url: map['url'],
    );
  }

  String toJson() => json.encode(toMap());

  factory Friends.fromJson(String source) =>
      Friends.fromMap(json.decode(source));
}
