import 'dart:convert';

// Generated by https://quicktype.io

class LocationPerson {
  String? id;
  String? latitud;
  String? longitud;
  String? nombre;
  String? pais;
  String? ciudad;

  LocationPerson({
    this.id,
    this.latitud,
    this.longitud,
    this.nombre,
    this.pais,
    this.ciudad,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'latitud': latitud,
      'longitud': longitud,
      'nombre': nombre,
      'pais': pais,
      'ciudad': ciudad,
    };
  }

  factory LocationPerson.fromMap(Map<String, dynamic>? map) {
    return LocationPerson(
      id: map!['id'],
      latitud: map['latitud'],
      longitud: map['longitud'],
      nombre: map['nombre'],
      pais: map['pais'],
      ciudad: map['ciudad'],
    );
  }

  String toJson() => json.encode(toMap());

  factory LocationPerson.fromJson(String source) =>
      LocationPerson.fromMap(json.decode(source));
}
