import 'dart:convert';

// Generated by https://quicktype.io

class RequestFriends {
  String? id;
  String? nombre;
  String? url;
  String? celular;
  String? email;
  String? latitud;
  String? longitud;
  String? fecNac;

  RequestFriends({
    this.id,
    this.nombre,
    this.url,
    this.celular,
    this.email,
    this.latitud,
    this.longitud,
    this.fecNac,
  });

  Map<String, dynamic> toMap() {
    return {
      'idusr': id,
      'nombre': nombre,
      'url': url,
      'celular': celular,
      'email': email,
      'latitud': latitud,
      'longitud': longitud,
      'fecNac': fecNac,
    };
  }

  factory RequestFriends.fromMap(Map<String, dynamic>? map) {
    return RequestFriends(
      id: map!['idusr'],
      nombre: map['nombre'],
      url: map['url'],
      celular: map['celular'],
      email: map['email'],
      latitud: map['latitud'],
      longitud: map['longitud'],
      fecNac: map['fecNac'],
    );
  }

  String toJson() => json.encode(toMap());

  factory RequestFriends.fromJson(String source) =>
      RequestFriends.fromMap(json.decode(source));
}
