class Autogenerated {
  Data? data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  List<TarjetaUs>? tarjetaUs;

  Data({this.tarjetaUs});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['tarjetaUs'] != null) {
      tarjetaUs = <TarjetaUs>[];
      json['tarjetaUs'].forEach((v) {
        tarjetaUs!.add(new TarjetaUs.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.tarjetaUs != null) {
      data['tarjetaUs'] = this.tarjetaUs!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class TarjetaUs {
  String? notarjeta;

  TarjetaUs({this.notarjeta});

  TarjetaUs.fromJson(Map<String, dynamic> json) {
    notarjeta = json['Notarjeta'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Notarjeta'] = this.notarjeta;
    return data;
  }
}
