name: hopapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animate_do: ^2.0.0
  cupertino_icons: ^1.0.3
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  google_fonts: ^2.1.0
  graphql_flutter: ^5.0.0
  local_auth: ^1.1.10
  pretty_qr_code: ^2.0.2
  qr_flutter: ^4.0.0
  rflutter_alert: ^2.0.4
  shimmer: ^2.0.0

dependency_overrides:
  mapbox_gl:
    git:
      url: https://github.com/tobrun/flutter-mapbox-gl.git
  # mapbox_gl_platform_interface:
  #   git:
  #     url: https://github.com/tobrun/flutter-mapbox-gl.git
  #     path: mapbox_gl_platform_interface
  # mapbox_gl_web:
  #   git:
  #     url: https://github.com/tobrun/flutter-mapbox-gl.git
  #     path: mapbox_gl_web

dev_dependencies:
  app_settings: ^4.0.4
  carousel_slider: ^4.0.0
  circular_profile_avatar: ^2.0.5
  datetime_picker_formfield: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.22.0
  flutter_test:
    sdk: flutter
  geolocator: ^7.6.0

  image_picker: ^0.8.4
  intl: ^0.17.0

  location: ^4.2.0
  # mapbox_gl: ^0.12.0
  # permission: ^0.1.7
  provider: ^6.0.0
  # qr_flutter: ^4.0.0
  shared_preferences: ^2.0.7
  vector_math: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon.jpg"
  adaptive_icon_background: "assets/icons/app-icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/login/
    - assets/qr/
    - assets/icons/
    - assets/markers/
    - assets/markers_google/
    - assets/menu_options/

